### ISSUE TITLE
Refactor to use Bet.AspNetCore Library

### ISSUE THREAD

**Issue by kdcllc** [kdcllc/dabarblog#13]
Remove and implement the functionality in this libary as listed:
- [x] [Add Azure Vault Support](https://github.com/kdcllc/Bet.AspNetCore/issues/1)
- [x] [Add Configuration Debugging information](https://github.com/kdcllc/Bet.AspNetCore/issues/2)
- [x] [Add HealthChecks support](https://github.com/kdcllc/Bet.AspNetCore/issues/3)
- [x] [Add Options Validation](https://github.com/kdcllc/Bet.AspNetCore/issues/5)
